name: On-QEMU non-intrusive CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup build env
      run: rustup target add thumbv7m-none-eabi
    - name: Build
      run: cargo build --verbose
    - name: Install Python 3 for test scripting
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install unittest
    - name: Install qemu dependencies
      run: apt install gdb-multiarch openocd qemu-system-arm
    - name: Run tests
      run: ./run_tests.sh
